################################################################################
# Reusable workflow: gp-init
#
# Reusable workflow for performing various initialization work as part of a
# deployment pipeline. Examples of such initialization:
# - Validating the CI/CD configuration against its JSON Schema
# - Enriching the configuration with computed values (concurrency groups,
#   stack directories, app name)
# - Uploading git metadata to Datadog
################################################################################
name: "Golden Path initialization"

on:
  workflow_call:
    inputs:
      config-file:
        description: "Path to CI/CD configuration file"
        type: string
        default: ".gp.cicd.json"
        required: false
      app-name:
        type: string
        required: true
        description: "The name of the application (e.g., `example`)"
      stack-name:
        type: string
        required: false
        description: "The name of the Terraform stack (e.g., `app-example`, `applications/app-example`)"
    outputs:
      config:
        description: "The processed CI/CD configuration"
        value: ${{ jobs.gp-init.outputs.config }}
    secrets:
      datadog-api-key:
        required: false
        description: "Datadog API key for git metadata upload"

jobs:
  gp-init:
    name: Initialization
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate config against schema
        env:
          CONFIG_FILE: ${{ inputs.config-file }}
        run: |
          schema_url="$(jq -r '."$schema" // empty' "$CONFIG_FILE")"
          if [ "$schema_url" == "" ]; then
          echo "::error::Config file $CONFIG_FILE is not using any schema."
            exit 1
          fi
          # renovate: datasource=pypi depName=check-jsonschema
          CHECK_JSONSCHEMA_VERSION="0.37.0"
          pip install --quiet "check-jsonschema==$CHECK_JSONSCHEMA_VERSION"
          check-jsonschema --schemafile "$schema_url" "$CONFIG_FILE"

      - name: Build config and store it as output
        id: config
        uses: oslokommune/composite-actions/build-gp-config@add-build-gp-config
        with:
          config-file: ${{ inputs.config-file }}
          app-name: ${{ inputs.app-name }}
          stack-name: ${{ inputs.stack-name }}

      - name: Upload git metadata
        env:
          DD_API_KEY: ${{ secrets.datadog-api-key }}
          DD_SITE: "datadoghq.eu"
        run: |
          # GitHub Actions does not support conditional checks on secrets,
          # so we need to do this check inside the step itself.
          if [ "$DD_API_KEY" == "" ]; then
            echo "No Datadog API key provided, skipping git metadata upload"
            exit 0
          fi
          # renovate: datasource=npm depName=@datadog/datadog-ci
          DATADOG_CI_VERSION="5.5.0"
          npx --ignore-scripts "@datadog/datadog-ci@$DATADOG_CI_VERSION" git-metadata upload
